Init
Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust pull request #1
Opened 2020-09-16 19:58 UTC by LilikF

Reméljük jó lett, igyekeztünk alaposan átnézni. Csak az első feladatot tartalmazza, kérlek nézzétek meg nekünk.

2020-09-19 16:13 UTC, wajzy requested changes
Az egyke eleve inkább antipattern, szerintem nem kell ide. Gondoljátok át a hit/sufferDamage függvényeket, aztán megnézem újra.

2020-09-19 16:13 UTC, wajzy commented on Character.cpp
> +    }
Ezt javaslom lecserélni egy felültöltött << operátort használó megoldásra.

2020-09-19 16:13 UTC, wajzy commented on Character.cpp
> +    }
Elegánsabb lenne egy másik Character objektumot (referenciáját) fogadni paraméterként, kiolvasni, hogy az mennyit tud sebezni, majd ennyivel csökkenteni az életerőt.

2020-09-19 16:13 UTC, wajzy commented on Character.cpp
> +    void Character::fight(Character* enemy) {
Ez most nem referencia, hanem mutató.

2020-09-19 16:13 UTC, wajzy commented on Character.cpp
> +                break;
Akkor már legyen itt is true/false!

2020-09-19 16:13 UTC, wajzy commented on Character.cpp
> +    }
Gondoljátok át, hogy szükség van-e a _hit_ ÉS a _sufferDamage_ függvényekre IS, vagy az egyiket esetleg el lehetne hagyni?

2020-09-19 16:13 UTC, wajzy commented on Utility.cpp
> +};
Hát ez így nem túl hasznos, akkor meg minek?

2020-09-19 16:13 UTC, wajzy commented on Utility.cpp
> +}
Szerintem feletsétek el az egyke mintát. Legyen egy statikus ellenőrző függvény az osztályban, és feladat megoldva.

2020-09-19 16:13 UTC, wajzy commented on main.cpp
> +    if (util->isNumber(argv[2]) && util->isNumber(argv[3]) && util->isNumber(argv[5]) && util->isNumber(argv[6]))
Ha statikus az isNumber, lehet rá az osztályával hivatkozni, nem kell példányosítás.

2020-09-19 19:53 UTC, LilikF commented
@wajzy 
Köszönjük a visszajelzést, kijavítottuk a kérdéses részeket.

2020-09-21 08:44 UTC, wajzy approved these changes
@hegyhati @LilikF  OK, elfogadom a módosításokat.

2020-09-21 15:08 UTC, merged