Second development task elkészült
Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust pull request #2
Opened 2020-09-24 17:57 UTC by NemesTom

parseUnit függvény létrehozva, main már fájlokat vár argumentumként, ebből az új formatnak megfelelő eredményeket ad. Van továbbá 3 unitunk, a GHA tesztet egy bash scripttel csináltuk meg, itt volt pár baki, figyelmetlenség ami a commitok nevéből és népességéből is látszik, de végül rájöttünk a hiba okára, így sikeresen lefut minden. Kérjük nézzétek meg, reméljük jó.

2020-09-26 10:54 UTC, oliverosz requested changes
A `results_correct`ben lévő különálló kimenetek gondolom már nem kellenek.

A README-ben frissítsétek a működés leírását!

A json parsolás a jelenlegi stádiumban megfelelő, majd úgyis tovább kell fejleszteni a későbbi feladatok során. A hibák inkább a többi részben vannak, akár az előző feladat megoldásában is. De főleg apróságok.

2020-09-26 10:54 UTC, oliverosz commented on .gitignore
> +/results/*
Ez elég fura megoldás. Normál esetben mindent verziókövetünk, néhány kivétellel, és nem fordítva. De tőlem maradhat.

2020-09-26 10:54 UTC, oliverosz commented on main.cpp
> +        delete player2;
Na ezért veszélyes a manuális memóriakezelés. Ránézésre jónak tűnik, de ha a 2 közül csak az egyiket sikerül létrehozni, akkor az nem lesz felszabadítva. Nyilván a mainben nem okoz nagy gondot egy ilyen hiba, de attól még hibás. Tőlem használhattok dinamikus memóriakezelést, de akkor legyen helyes.

2020-09-26 10:54 UTC, oliverosz commented on main.cpp
> +        cout << "Incorrect input parameters. Please check if the input file paths you entered were correct." << endl;
Itt meg illene valami nemnulla visszatérési érték.

2020-09-26 10:54 UTC, oliverosz commented on Utility.h
> +        static std::vector<std::string> split(std::string, char);
Ha csak static metódusai vannak az osztálynak, akkor az inkább egy namespace, helyesebb lenne annak hívni. Mert most megengedi, hogy példányosítsák, aminek meg nincs értelme. De amúgy :+1: a utility függvények külön fájlba szervezéséért, csak szebb lenne erre namespace-t használni.

2020-09-26 10:54 UTC, oliverosz commented on Utility.cpp
> +#include <fstream>
A vector és a string már include-olva van a `Utility.h` által, felesleges ide.
A `ctype.h` az C-s header, C++-ban a `cctype` használandó helyette.

2020-09-26 10:54 UTC, oliverosz commented on Utility.cpp
> +bool Utility::isNumber(std::string input)
Ne másolgassuk feleslegesen az objektumokat, a paraméter legyen const referencia.

2020-09-26 10:54 UTC, oliverosz commented on Utility.cpp
> +    for (char c : input)
Itt meg további felesleges másolások minden karakterre. `for (const char& c : input)`

2020-09-26 10:54 UTC, oliverosz commented on Utility.cpp
> +std::vector<std::string> Utility::split(std::string s, char splitChar)
Szintén const ref paraméter legyen a string.

2020-09-26 10:54 UTC, oliverosz commented on Utility.cpp
> +	std::string current_value = "";
A default konstruktor is üres stringet hoz létre, felesleges az `= ""`.

2020-09-26 10:54 UTC, oliverosz commented on Character.h
>      std::string getName() const;
Itt is referencia legyen a string paraméter, illetve a getName se másolatot adjon vissza az adattagból, hanem const referenciát.

2020-09-26 10:54 UTC, oliverosz commented on Character.cpp
> +            this->HP = 0;
Felesleges ez a sok `this`, a tagfüggvényben scope-ban vannak az adattagok és más metódusok.

2020-09-26 10:54 UTC, oliverosz commented on run_test.sh
> +./a.out units/Tolvaj.json units/Robin.json >> results.txt
Az elsőnél jobb lenne `>`-t használni, hogy ha már létezik a fájl, írja felül. És akkor lokálisan egymás után többször is futtatható.

2020-09-26 10:54 UTC, oliverosz commented on Character.cpp
> +            std::string fileContents = s.str();
Így is jó, de ez stringstream nélkül is megoldható: `std::getline(f, fileContents, '\0');`

2020-09-28 16:07 UTC, oliverosz commented on Utility.cpp
> +		if (c) delete c;
Nem kell az `if (c)`. A `delete nullptr` nem csinál semmit.

2020-09-28 16:07 UTC, oliverosz commented on Character.h
>      std::string getName() const;
A 2. fele még nincs meg.

2020-09-28 16:08 UTC, oliverosz commented on Utility.h
> +        static std::vector<std::string> split(std::string, char);
Csak annyit kell csinálni, hogy `class` helyett `namespace`-t kell írni, és kitörölni a `public:` meg a `static` szavakat.

2020-09-28 16:09 UTC, oliverosz requested changes
Bár még nem kértetek újabb reviewt, átnéztem, mi hiányzik még. Kommentekben jeleztem.

2020-09-28 16:40 UTC, LilikF commented
@oliverosz Köszönjük, gyorsan ledolgoztam őket, remélem jó lett így. Egyedül a stringstream helyetti std::getline null delimiteres dologgal vagyok meglőve, akárhogy próbálom nem olvas be semmit úgy, és neten se nagyon találtam rá példát. Lehet hogy én szúrok el valamit, ha nagyon fontos akkor beszélek még a srácokkal és megpróbáljuk megoldani. Ha viszont jó a stringstream is, akkor megköszönnénk ha így is átmenne a PR.

2020-09-28 16:46 UTC, oliverosz approved these changes
@LilikF Nem tudom, mi lehet a baj a getline-nal. Én kipróbáltam, és működött. De jó a stringstream is.

@hegyhati merge into master, Master

2020-09-28 16:46 UTC, oliverosz commented on Character.cpp
> +    int const & Character::getHP() const
Egyszerű típusoknál felesleges referenciát visszaadni, ott a másolás nem hív meg másoló konstruktort, meg csak 4 bájt az egész. De mindegy, maradhat.

2020-09-28 16:51 UTC, LilikF commented on Character.cpp
> +    int const & Character::getHP() const
Áh, értem. Ezt nem tudtam, köszönöm!

2020-10-03 09:04 UTC, LilikF commented
@hegyhati 
@oliverosz feljebb jelezte, hogy jó lesz így a PR. Be tudnád mergelni nekünk a masterbe? Kezdenék dolgozni az új feladaton, de talán szerencsésebb ha nem egy levegőben lógó branchről ágazok el, hanem a masterről (bár különbség nem lesz a kettő között már, de azért mégis). Köszönjük!

2020-10-06 07:18 UTC, merged