Jsonparser, cmake, unit tesztek
Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust pull request #6
Opened 2020-10-15 14:55 UTC by LilikF

@wajzy Elkészítettem a branch feladatait, elnézést hogy ennyire a beadási határidő végére hagytam.  Remélem hogy jó, a feladatleíráshoz viszonyítva úgy érzem hozza az elvártat, de nem vagyok minden részletében biztos (például a JSON parse-nál továbbra is feltételeztem, hogy helyes adatot kapunk, ahogyan egy korábbi feladatnál volt. Emiatt kifejezetten részletes kivételkezelést nem írtam).

2020-10-18 16:17 UTC, wajzy requested changes
Ez a program nem lenne rossz, ha nem feltételezné a tökéletes bemenetet. Most már ideje felkészíteni legalább néhány lehetséges problémára, és a működését tesztesetekkel ellenőrizni.

2020-10-18 16:17 UTC, wajzy commented on Character.cpp
> +            float dmg = std::any_cast<float>(parsedMap["dmg"]);
Én itt figyelnék az esetleges kivételekre, mert az átalakítás nem biztos, hogy menni fog.

2020-10-18 16:17 UTC, wajzy commented on Utility.cpp
> +		//Delete spaces from the value - we can assume the values are correct, as stated in the task description
Hát, már ne feltételezd. Legalább néhány egyszerű problémára készítsd fel a parzert, pl. hiányzó :-ra.

2020-10-21 11:44 UTC, LilikF commented
@wajzy 
Felkészítettem a parsert egyszerű hibákra (hiányzó '{' vagy '}' a fájl elején és végén, hiányzó ' : ' vagy ' " ' karakterek, nem parsolható számértékek a parseUnit metódusban. Két tesztet is írtam rá a googleTest.cpp-be, remélem megfelelő így a branch.

2020-10-24 15:07 UTC, wajzy approved these changes
Legyen.

2020-10-24 15:08 UTC, wajzy commented
@LilikF Oldd fel az ütközéseket!

2020-10-27 15:19 UTC, LilikF commented
@wajzy Feloldottam az ütközéseket.

2020-10-30 20:23 UTC, NemesTom commented
@wajzy, kérhetünk egy merge-et? Múltkor véletlenül mi mergeltünk a master branchre amit nem szabadott volna.

2020-10-31 09:34 UTC, merged