Refactor
Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust pull request #9
Opened 2020-11-02 09:17 UTC by LapatKrisz

@hegyhati elkészült a refactor branch, megköszönnénk ha megnéznéd nekünk

2020-11-02 17:01 UTC, NemesTom commented
@hegyhati Ha ok a branch és mehet masterbe, amint kapjuk a mailt oldjuk is a conflictokat - elméletileg nem lesznek - majd csináljuk a unittest branchet. Ha megkérhetünk a csapat hozzárendelést ([Pottyok ](https://github.com/Teaching-projects/SZE-MOSZE-2020-Pottyok)csapat tagjai) is meg tudod, tudjátok csinálni egyúttal? Sajnos kicsit megcsúsztunk az idővel.

2020-11-03 09:17 UTC, hegyhati requested changes
most van az "uj" parsefromFile, ami egy JSON-t ad vissza, meg vannak a regiek, amik egy map-et. Az elobbibol a get szedeget ki, az utobbibol meg stoi-ztok. Ez ket teljesen parhuzamos mukodes, ami csak kaoszhoz vezet, tessek egysegesiteni.

2020-11-03 09:49 UTC, hegyhati commented
A csapathozzarendelest megcsinaltam, bar az kulon issue-ban jobban kovetheto lett volna, mert ehhez a PR-hez semmi koze :)

2020-11-03 09:57 UTC, LilikF commented
@hegyhati Igaz, a JSON parserben volt egy kis keveredés. Most átírtam, hogy a JSON classban eltárolt adatokat tartalmazó map eleve protected, és csak a JSON::get<type>-ból lehessen megkapni a tartalmat, valamint ne kelljen utólagos konverzió, hanem eleve any_casttal adja vissza.

2020-11-03 10:25 UTC, hegyhati approved these changes

2020-11-03 10:25 UTC, merged